version: '3.9'

services:
  db:
    image: mysql:8.4 # Es mejor fijar la versión que ya vimos que funciona
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 10s # Un poco más de margen para no saturar al inicio
      timeout: 5s
      retries: 5
    ports:
          - "3307:3306"

  api:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    # Usamos la sintaxis de lista para evitar problemas de parsing con los flags
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  mysql_data: